server:
  servlet:
    context-path: /

familie:
  ef:
    sak:
      url: https://api-gw.oera.no/familie-ef-sak/api/
spring:
  data:
    jdbc:
      repositories:
        enabled: true
#  flyway:
#    schemas: "familie-ef-mottak"
#    enabled: true
