server:
  port: 8092
  servlet:
    context-path: /

spring:
  datasource:
    username: familie
    password: Test
    url: jdbc:postgresql://localhost:5432/familie-ef-mottak

familie:
  ef:
    sak:
      url: http://localhost:8093/api/
    arkiv:
      url:

logging:
  config: "classpath:logback-test.xml"

no.nav.security.jwt:
#  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
    proxyurl:
  client:
    registration:
      ef-sak-clientcredentials:
        resource-url: http://localhost:8083/api
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: anything0
        authentication:
          client-id: anything1
          client-secret: anything2
          client-auth-method: client_secret_basic
      ef-arkiv-clientcredentials:
        resource-url: http://localhost:8085/api
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: anything4
        authentication:
          client-id: anything5
          client-secret: anything6
          client-auth-method: client_secret_basic

example:
  database:
    encryption:
      # 16, 24 or 32 bytes
      key: Det finnes mange gode eksempler.
